// ─────────────────────────────────────────────────────────────────────────────
// Every code the mental wellness (rehabilitation) templates and their
// extraction maps use, in one system. The 22 questionnaires in
// input/mental-health-templates carry their answer options on it, and the
// extraction StructureMaps stamp its codes onto everything they create, so a
// consumer needs exactly one CodeSystem to read what the forms produce.
//
// Three kinds of concept live here, and the comment banners mark them out:
// instrument and document types the maps assert; answer options the forms
// offer; and question or clause codes, whose code is the question item's own
// linkId (or its suffix after the first dot where the map says so), so adding
// a question to a template carries its concept through without editing a map.
//
// Generated from the templates; regenerate rather than hand-edit when a
// template changes (scripts live with the assessment work).
// ─────────────────────────────────────────────────────────────────────────────

CodeSystem: MentalWellnessCodeSystem
Id: mental-wellness-codesystem
Title: "Mental Wellness Code System"
Description: "A single code system for the mental wellness and rehabilitation templates: the instruments and document types their extractions assert, the answer options the forms offer, and the question and clause concepts their answers hang off. One system rather than two dozen invented ones, so every extracted resource is readable against one published vocabulary."
* ^status = #active
* ^experimental = false
* ^caseSensitive = true
* ^content = #complete

// ── Assessment instruments and clinical record types ──
* #stage-of-change "Stage of change"
* #general-physical-examination "General physical examination"
* #clinical-history "Clinical history"
* #mental-state-examination "Mental state examination"
* #clinical-formulation "Clinical formulation"
* #bdi "Beck's Depression Inventory"
* #chemical-use-history "Chemical use history"

// ── Assessment domains (shared by the ASI and the SOAP problem areas) ──
* #general-information "General information"
* #medical "Medical status"
* #employment "Employment and support status"
* #alcohol-drug "Alcohol and drug use"
* #legal "Legal status"
* #family-social "Family and social relationships"
* #psychiatric "Psychiatric status"

// ── Clinical risk flags ──
* #suicidal-thoughts-reported "Serious thoughts of suicide reported"
* #suicide-attempt-reported "Suicide attempt reported"
* #suicidal-thoughts-observed "Suicidal thoughts observed at interview"
* #suicidal-ideation-reported "Suicidal ideation reported"

// ── Document and agreement types ──
* #follow-up-agreement "Follow-up agreement"
* #discharge-against-advice "Discharge against medical advice"
* #case-conference "Case conference note"
* #possessions-receipt "Client possessions receipt"
* #discharge-clearance-summary "Discharge clearance summary"
* #continuation-sheet "Continuation sheet"
* #financial-agreement "Financial agreement"
* #family-session "Family session note"
* #admission-soap-note "Admission SOAP note"
* #code-of-ethics "Code of ethics agreement"

// ── Consent categories ──
* #confidentiality-exceptions "Exceptions to confidentiality"
* #client-rights-responsibilities "Client rights and responsibilities"
* #evaluation-and-treatment "Consent for evaluation and treatment"
* #house-rules "House rules acknowledgement"

// ── Discharge clearance and its departments ──
* #discharge-clearance "Discharge clearance"
* #adminAccounts "Admin / Accounts"
* #primaryCounsellor "Primary counsellor"
* #store "Store"
* #socialWork "Social work"
* #libraryNhif "Library / NHIF"
* #pharmacyNursing "Pharmacy / Nursing"
* #dischargeOfficer "Discharge officer"
* #securityOfficer "Security officer"

// ── Clearance reasons ──
* #referral "Referral"
* #completion "Completion"
* #withdrawal "Withdrawal"

// ── Communication categories ──
* #aftercare-follow-up "Aftercare follow-up"

// ── Client education curriculum lessons ──
* #client-education "Client education"
* #orientation "Orientation"
* #selfAcceptance "Self-acceptance and denial management"
* #rootCause "Identifying the root cause of addiction"
* #understandingAddiction "Understanding addiction"
* #effects "Effects of drugs and alcohol, including the correlation with HIV/AIDS"
* #selfEsteem "Low self-esteem"
* #timeAndLeisure "Time and leisure management"
* #higherPower "The concept of a higher power or God"
* #prayer "Prayer, meditation and devotion"
* #summaryEarly "Summary and preparation for late recovery"
* #anger "Anger and emotion management"
* #characterDefects "Identifying and overcoming character and personality defects"
* #personalityPrinciples "Personality and principles"
* #guiltShameStress "Managing guilt, shame and stress"
* #virtuesValues "Virtues, values and attitude"
* #summaryLate "Summary and preparation for the maintenance stage"
* #familyCommunity "Family, friends and community"
* #selfWorth "Self-worth and respect"
* #lifeSkills "Life skills training"
* #relapsePrevention "Slip and relapse prevention and management"
* #vocation "Vocation and preparation for re-integration"
* #celebrating "Celebrating recovery"
* #summaryGraduation "Summary and preparation for graduation"
* #graduation "Graduation from the programme"

// ── Admission consent clauses (shared with the house rules form) ──
* #consent.treatment "I wish to undertake the rehabilitation programme, which has been explained to me, and I ..."
  * ^definition = "I wish to undertake the rehabilitation programme, which has been explained to me, and I consent to treatment as advised and recommended."
* #consent.duration "I understand that the programme takes a minimum of ninety (90) days, and I agree to the ..."
  * ^definition = "I understand that the programme takes a minimum of ninety (90) days, and I agree to the terms and conditions below for that period."
* #cardinalRules.drugs "Drugs: I shall not at any time use or be found in possession of drugs, within or outside ..."
  * ^definition = "Drugs: I shall not at any time use or be found in possession of drugs, within or outside the premises, during the treatment period."
* #cardinalRules.sex "Sex: no sexual act of any kind is acceptable during the treatment period."
* #cardinalRules.violence "Violence: no verbal, physical or emotional abuse, including threats to staff or fellow ..."
  * ^definition = "Violence: no verbal, physical or emotional abuse, including threats to staff or fellow clients, is allowed."
* #cardinalRules.property "Destruction of property: I shall respect the property of clients, staff, the centre and ..."
  * ^definition = "Destruction of property: I shall respect the property of clients, staff, the centre and the neighbourhood; destroying it will be penalised."
* #cardinalRules.theft "Theft: no theft of property belonging to fellow clients, staff, the centre or neighbours ..."
  * ^definition = "Theft: no theft of property belonging to fellow clients, staff, the centre or neighbours will be tolerated."
* #groundNorms.permission "I shall never leave the compound without permission from staff."
* #groundNorms.stealing "I shall not steal or abuse."
* #groundNorms.hygiene "I shall maintain the required standards of hygiene."
* #groundNorms.abstinence "I shall abstain from all mood-altering substances."
* #groundNorms.programme "I shall adhere to the daily programme and all required activities, and shall not abscond ..."
  * ^definition = "I shall adhere to the daily programme and all required activities, and shall not abscond from the programme or any of its activities."
* #groundNorms.conduct "I shall be responsible and uphold the set virtues and the moral and spiritual standards."
* #groundNorms.prohibitedItems "I shall not be found in possession of illegal items, for example knives, phones or drugs."

// ── Client rights and responsibilities clauses ──
* #rights.informed "To be informed of your rights verbally and in writing, and to extend those same rights to ..."
  * ^definition = "To be informed of your rights verbally and in writing, and to extend those same rights to fellow clients in treatment and to the management and staff of the centre."
* #rights.confidentiality "To have the confidentiality of your treatment and treatment records protected. ..."
  * ^definition = "To have the confidentiality of your treatment and treatment records protected. Information about your treatment will not be disclosed to any person or agency without your written permission, except where the law requires disclosure."
* #rights.limitsOfConfidentiality "To know the limits of confidentiality and the situations in which the clinician or the ..."
  * ^definition = "To know the limits of confidentiality and the situations in which the clinician or the centre is legally required to disclose information."
* #rights.informedConsent "To give informed consent, acknowledging your permission for the centre to provide ..."
  * ^definition = "To give informed consent, acknowledging your permission for the centre to provide treatment."
* #rights.promptTreatment "To receive prompt and adequate treatment, and to refuse treatment you do not want."
* #rights.medication "To be free from unnecessary or excessive medication, and to receive clear information ..."
  * ^definition = "To be free from unnecessary or excessive medication, and to receive clear information about any recommended medication, its possible benefits, side effects and alternatives."
* #rights.safeEnvironment "To be provided a safe environment, free from physical, sexual and emotional abuse."
* #rights.treatmentPlan "To receive complete and accurate information about your treatment plan, its goals ..."
  * ^definition = "To receive complete and accurate information about your treatment plan, its goals, methods, potential risks, benefits and progress."
* #rights.fees "To receive information about fees, payment methods, co-payment, and the length and ..."
  * ^definition = "To receive information about fees, payment methods, co-payment, and the length and duration of sessions and treatment."
* #rights.qualifiedProviders "To receive services from providers who are qualified and competent."
* #rights.clinicianCapabilities "To receive information about the professional capabilities and limitations of any ..."
  * ^definition = "To receive information about the professional capabilities and limitations of any clinician involved in your treatment."
* #rights.recording "To be free from audio or video recording without informed consent."
* #rights.recordAccess "To have access to information in your treatment records, with the approval of the ..."
  * ^definition = "To have access to information in your treatment records, with the approval of the clinical coordinator, during treatment."
* #rights.recordsForwarded "To have information forwarded to a new clinician following your treatment at this ..."
  * ^definition = "To have information forwarded to a new clinician following your treatment at this facility."
* #rights.grievance "To file a grievance if your rights have been denied or limited, verbally or in writing to ..."
  * ^definition = "To file a grievance if your rights have been denied or limited, verbally or in writing to the clinical coordinator, and to receive information about the grievance procedure in writing."
* #responsibilities.participate "To follow and fully participate in the outlined treatment programme of the centre."
* #responsibilities.fullInformation "To provide full information about yourself, to enable a proper assessment."
* #responsibilities.askQuestions "To ask questions and understand your condition."
* #responsibilities.respect "To show respect to the staff and other clients in the centre."
* #responsibilities.goalPlanning "To participate in planning your goals for treatment."
* #responsibilities.cooperate "To cooperate in treatment planning."
* #responsibilities.rules "To fully abide by the centre's rules and regulations as stipulated."

// ── Confidentiality exception clauses ──
* #exceptions.imminentHarm "It is necessary to protect you or someone else from imminent physical harm."
* #exceptions.courtOrder "The centre receives a valid court order or subpoena that mandates release of your ..."
  * ^definition = "The centre receives a valid court order or subpoena that mandates release of your information."
* #exceptions.abuseReporting "The centre is reporting abuse of children, the elderly, or persons with disabilities."
* #exceptions.internalConsultation "Clinicians within the agency consult with each other about your treatment in order to ..."
  * ^definition = "Clinicians within the agency consult with each other about your treatment in order to provide the best possible care."
* #acknowledgement.agreed "I acknowledge that I have read, understood and agreed with the above information."

// ── Guardian treatment consent clauses ──
* #acknowledgements.consent "I voluntarily consent that the client will take part in a mental health evaluation and/or ..."
  * ^definition = "I voluntarily consent that the client will take part in a mental health evaluation and/or treatment — psychological or psychiatric — to help them overcome substance use disorder and other mental health problems."
* #acknowledgements.conductedBy "I understand the evaluation or treatment will be conducted by a psychologist, addiction ..."
  * ^definition = "I understand the evaluation or treatment will be conducted by a psychologist, addiction professional, psychiatrist or psychiatric nurse practitioner, or by someone supervised by one of them, and within the boundaries of the relevant Kenyan law."
* #acknowledgements.duration "Duration and charges: the minimum duration of treatment is ninety (90) days, and I have ..."
  * ^definition = "Duration and charges: the minimum duration of treatment is ninety (90) days, and I have been informed of the charges for those ninety days."
* #acknowledgements.absconding "Absconding: I have been informed of the possibility and consequences of the client ..."
  * ^definition = "Absconding: I have been informed of the possibility and consequences of the client absconding from the centre or any other location during treatment. The centre shall not be held responsible for the consequences, and I shall not claim compensation or damages in any form."
* #acknowledgements.dischargeAgainstAdvice "Discharge against the centre's advice: I have been informed of the possibility and ..."
  * ^definition = "Discharge against the centre's advice: I have been informed of the possibility and consequences, and understand such a discharge may adversely affect the client's progress and recovery."
* #acknowledgements.relapse "Relapse: I acknowledge that relapse is possible after treatment if the necessary ..."
  * ^definition = "Relapse: I acknowledge that relapse is possible after treatment if the necessary aftercare support is not adequately provided by family and significant others, and that the centre shall not be held responsible for it."
* #acknowledgements.compensation "Compensation: I agree that I shall not be compensated for any accidental or incidental ..."
  * ^definition = "Compensation: I agree that I shall not be compensated for any accidental or incidental occurrence affecting the client during the treatment period, whether inside or outside the centre."

// ── Chemical use history questions ──
* #history.firstDrink "How old were you when you had your first drink? Describe what happened and how you felt."
* #history.drugsUsed "List all of the drugs you have ever used, and the age at which you first used each one."
* #history.habits "What are your drug-using habits? Where do you use? With whom? Under what circumstances?"
* #history.heavyPeriod "Was there ever a period in your life when you used too much or too often? Explain."
* #history.problemsCaused "Has using chemicals ever caused a problem for you? Describe the problem or problems."
* #history.moreThanIntended "When you were using, did you find that you used more, or for longer, than you had ..."
  * ^definition = "When you were using, did you find that you used more, or for longer, than you had originally intended? Give some examples."
* #history.tolerance "Do you have to use more of the chemical now to get the same effect? How much more than ..."
  * ^definition = "Do you have to use more of the chemical now to get the same effect? How much more than when you first started?"
* #history.cuttingDown "Did you ever try to cut down, and what happened to your attempt?"
* #history.cuttingDownHow "What did you do to cut down? Did you change your beverage, limit the amount, or restrict ..."
  * ^definition = "What did you do to cut down? Did you change your beverage, limit the amount, or restrict your use to a certain time of day?"
* #history.stoppedCompletely "Did you ever stop using completely? What happened? Why did you start again?"
* #history.timeIntoxicated "Did you spend a lot of time intoxicated or hung over?"
* #history.dangerousUse "Did you ever use while doing something dangerous, such as driving a car? Give some ..."
  * ^definition = "Did you ever use while doing something dangerous, such as driving a car? Give some examples."
* #history.missedWork "Were you ever so high, or so hung over, that you missed work or school? Give some ..."
  * ^definition = "Were you ever so high, or so hung over, that you missed work or school? Give some examples."
* #history.missedFamilyEvents "Did you ever miss family events because you were high or hung over? Give a few examples."
* #history.familyProblems "Did you ever cause family problems? Give examples."
* #history.annoyedWhenChallenged "Did you ever feel annoyed when someone talked to you about your drinking or drug use? Who ..."
  * ^definition = "Did you ever feel annoyed when someone talked to you about your drinking or drug use? Who was it, and what did they say?"
* #history.guilt "Did you ever feel bad or guilty about your use? Give examples."
* #history.psychologicalProblems "Did using ever cause you psychological problems, such as being depressed? Explain the ..."
  * ^definition = "Did using ever cause you psychological problems, such as being depressed? Explain the problem, with examples."
* #history.physicalProblems "Did using ever cause physical problems, or make a physical problem worse? Give a few ..."
  * ^definition = "Did using ever cause physical problems, or make a physical problem worse? Give a few examples."
* #history.blackouts "Did you ever have a blackout? How old were you when you had your first one? Give some ..."
  * ^definition = "Did you ever have a blackout? How old were you when you had your first one? Give some examples."
* #history.sickFromUse "Did you ever get sick because you were too intoxicated? Give some examples."
* #history.badHangovers "Did you ever have a really bad hangover? Describe how you felt."
* #history.withdrawal "Did you ever get the shakes or suffer withdrawal symptoms when you quit using? Describe ..."
  * ^definition = "Did you ever get the shakes or suffer withdrawal symptoms when you quit using? Describe what happened when you stopped."
* #history.useToAvoidWithdrawal "Did you ever use to avoid withdrawal symptoms? Give examples of when you used a substance ..."
  * ^definition = "Did you ever use to avoid withdrawal symptoms? Give examples of when you used a substance to control them."
* #history.previousHelp "Have you ever sought help for your drug problem? When? Who did you see? Did the treatment ..."
  * ^definition = "Have you ever sought help for your drug problem? When? Who did you see? Did the treatment help, and how?"
* #history.reasonsToContinue "Why do you want to continue to use? Give five reasons."
* #history.reasonsToStop "Why do you want to stop using? Give ten reasons."
* #history.reputation "Has alcohol or drug use ever affected your reputation? Describe what happened and how you ..."
  * ^definition = "Has alcohol or drug use ever affected your reputation? Describe what happened and how you felt, and how you feel about yourself now."
* #history.financialImpact "How has using affected you financially? Give a few examples of money wasted in your ..."
  * ^definition = "How has using affected you financially? Give a few examples of money wasted in your addiction."
* #history.selfImage "Has your addiction changed how you feel about yourself? Give some examples."
* #history.ambition "Has your ambition decreased since you started using? Give some examples."
* #history.selfConfidence "Are you as self-confident as you were before?"
* #history.whyTreatmentNow "Describe the reasons why you want treatment now."

// ── Addiction severity index questions ──
* #general.G1 "G1. Client's IP number"
* #general.G2 "G2. Date of admission"
* #general.G3 "G3. Date of birth"
* #general.G4 "G4. Date of interview"
* #general.G5 "G5. Time begun"
* #general.G6 "G6. Time ended"
* #general.G7 "G7. Interviewer's name"
* #general.G8 "G8. Special circumstances for not doing the assessment"
* #general.G8s "G8. If other, specify"
* #general.G9 "G9. Residence — whom are you living with?"
* #general.G9s "G9. If other, specify"
* #general.G10 "G10. Is this residence owned by you or your parents?"
* #general.G10s "G10. If others, specify"
* #general.G11 "G11. How long have you lived at your current address?"
* #general.G12 "G12. Do you have a religious preference?"
* #general.G12s "G12. If other, specify"
* #general.G13 "G13. Have you been in a controlled environment in the past 30 days? (a place ..."
  * ^definition = "G13. Have you been in a controlled environment in the past 30 days? (a place theoretically without access to drugs)"
* #general.G13s "G13. If other, specify"
* #general.G14 "G14. How many days?"
* #general.comments "Further information and comments (quote the question number)"
* #medical.M1 "M1. How many times in your life have you been hospitalised for medical problems? (include ..."
  * ^definition = "M1. How many times in your life have you been hospitalised for medical problems? (include overdoses and DTs; exclude detox, alcohol/drug and psychiatric treatment, and uncomplicated childbirth)"
* #medical.M2 "M2. How long ago was your last hospitalisation for a medical problem?"
* #medical.M3 "M3. Do you have any chronic medical problems which continue to interfere with your life?"
* #medical.M4 "M4. Are you taking any prescribed medication on a regular basis for a medical problem?"
* #medical.M5 "M5. How many days have you experienced medical problems in the past 30 days?"
* #medical.M5s "M5. Specify the problem"
* #medical.M6 "M6. How troubled or bothered have you been by these medical problems in the past 30 days?"
* #medical.M7 "M7. How important to you now is treatment for these medical problems?"
* #medical.M8 "M8. Interviewer severity rating: the patient's need for medical treatment"
* #medical.M9 "M9. Is the above information significantly distorted by the patient's misrepresentation?"
* #medical.M10 "M10. Is the above information significantly distorted by the patient's inability to ..."
  * ^definition = "M10. Is the above information significantly distorted by the patient's inability to understand?"
* #medical.M11 "M11. Is the above information significantly distorted by the patient's resistance to ..."
  * ^definition = "M11. Is the above information significantly distorted by the patient's resistance to treatment?"
* #medical.comments "Further information and comments (quote the question number)"
* #employment.E1 "E1. Education completed"
* #employment.E2 "E2. Training or technical education completed"
* #employment.E3 "E3. Do you have a profession, trade or skill?"
* #employment.E3s "E3. If yes, specify"
* #employment.E4 "E4. Do you have a valid driver's licence?"
* #employment.E5 "E5. Do you have a full-time job? (35+ hours weekly)"
* #employment.E6 "E6. If not, what is your occupation?"
* #employment.E7 "E7. Does someone contribute to your support in any way?"
* #employment.E8 "E8. Does this support constitute the majority of your support?"
* #employment.E9 "E9. What is your usual employment pattern over the past 3 years?"
* #employment.E10 "E10. How many people depend on you for the majority of their food, shelter and so on?"
* #employment.E11 "E11. How many days have you experienced employment problems in the past 30?"
* #employment.E12 "E12. How troubled or bothered have you been by these employment problems in the past 30 ..."
  * ^definition = "E12. How troubled or bothered have you been by these employment problems in the past 30 days?"
* #employment.E13 "E13. How important to you now is counselling for these employment problems?"
* #employment.E14 "E14. Interviewer severity rating: the patient's need for employment counselling"
* #employment.E15 "E15. Is the above information significantly distorted by the client's misrepresentation?"
* #employment.E16 "E16. Is the above information significantly distorted by the client's inability to ..."
  * ^definition = "E16. Is the above information significantly distorted by the client's inability to understand?"
* #employment.E17 "E17. Is the above information significantly distorted by the patient's resistance to ..."
  * ^definition = "E17. Is the above information significantly distorted by the patient's resistance to treatment?"
* #employment.comments "Further information and comments (quote the question number)"
* #drugs.D1.days "D1. Alcohol — days used in the past 30"
* #drugs.D1.years "D1. Alcohol — lifetime years of use"
* #drugs.D1.route "D1. Alcohol — route of administration"
* #drugs.D2.days "D2. Alcohol (used to intoxication) — days used in the past 30"
* #drugs.D2.years "D2. Alcohol (used to intoxication) — lifetime years of use"
* #drugs.D2.route "D2. Alcohol (used to intoxication) — route of administration"
* #drugs.D3.days "D3. Heroin — days used in the past 30"
* #drugs.D3.years "D3. Heroin — lifetime years of use"
* #drugs.D3.route "D3. Heroin — route of administration"
* #drugs.D4.days "D4. Methadone — days used in the past 30"
* #drugs.D4.years "D4. Methadone — lifetime years of use"
* #drugs.D4.route "D4. Methadone — route of administration"
* #drugs.D5.days "D5. Other opiates or analgesics — days used in the past 30"
* #drugs.D5.years "D5. Other opiates or analgesics — lifetime years of use"
* #drugs.D5.route "D5. Other opiates or analgesics — route of administration"
* #drugs.D5.specify "D5. Other opiates or analgesics — specify"
* #drugs.D6.days "D6. Barbiturates — days used in the past 30"
* #drugs.D6.years "D6. Barbiturates — lifetime years of use"
* #drugs.D6.route "D6. Barbiturates — route of administration"
* #drugs.D6.specify "D6. Barbiturates — specify"
* #drugs.D7.days "D7. Other sedatives, hypnotics or tranquillisers — days used in the past 30"
* #drugs.D7.years "D7. Other sedatives, hypnotics or tranquillisers — lifetime years of use"
* #drugs.D7.route "D7. Other sedatives, hypnotics or tranquillisers — route of administration"
* #drugs.D7.specify "D7. Other sedatives, hypnotics or tranquillisers — specify"
* #drugs.D8.days "D8. Cocaine — days used in the past 30"
* #drugs.D8.years "D8. Cocaine — lifetime years of use"
* #drugs.D8.route "D8. Cocaine — route of administration"
* #drugs.D8.specify "D8. Cocaine — specify"
* #drugs.D9.days "D9. Amphetamines — days used in the past 30"
* #drugs.D9.years "D9. Amphetamines — lifetime years of use"
* #drugs.D9.route "D9. Amphetamines — route of administration"
* #drugs.D9.specify "D9. Amphetamines — specify"
* #drugs.D10.days "D10. Cannabis — days used in the past 30"
* #drugs.D10.years "D10. Cannabis — lifetime years of use"
* #drugs.D10.route "D10. Cannabis — route of administration"
* #drugs.D11.days "D11. Hallucinogens — days used in the past 30"
* #drugs.D11.years "D11. Hallucinogens — lifetime years of use"
* #drugs.D11.route "D11. Hallucinogens — route of administration"
* #drugs.D11.specify "D11. Hallucinogens — specify"
* #drugs.D12.days "D12. Inhalants — days used in the past 30"
* #drugs.D12.years "D12. Inhalants — lifetime years of use"
* #drugs.D12.route "D12. Inhalants — route of administration"
* #drugs.D12.specify "D12. Inhalants — specify"
* #drugs.D13 "D13. According to the interviewer, which substance is or are the major problem?"
* #drugs.D14 "D14. How long was your last period of voluntary abstinence from this major substance? ..."
  * ^definition = "D14. How long was your last period of voluntary abstinence from this major substance? (months; 0 = never abstinent)"
* #drugs.D15 "D15. How many months ago did this abstinence end? (1 = still abstinent)"
* #drugs.D16 "D16. How many times have you had alcohol DTs?"
* #drugs.D17 "D17. How many times have you overdosed on drugs?"
* #drugs.D18 "D18. How many times in your life have you been treated for alcohol abuse?"
* #drugs.D19 "D19. How many times in your life have you been treated for drug abuse?"
* #drugs.D20 "D20. How many of these alcohol treatments were detox only?"
* #drugs.D21 "D21. How many of these drug treatments were detox only?"
* #drugs.D22 "D22. How much money did you spend on alcohol in the past 30 days? (KES)"
* #drugs.D23 "D23. How much money did you spend on drugs in the past 30 days? (KES)"
* #drugs.D24 "D24. How many days in the past 30 have you experienced alcohol problems?"
* #drugs.D25 "D25. How many days in the past 30 have you experienced drug problems?"
* #drugs.D26 "D26. How troubled or bothered have you been in the past 30 days by alcohol problems?"
* #drugs.D27 "D27. How troubled or bothered have you been in the past 30 days by drug problems?"
* #drugs.D28 "D28. How important to you now is treatment for these alcohol problems?"
* #drugs.D29 "D29. How important to you now is treatment for these drug problems?"
* #drugs.D30 "D30. Interviewer severity rating: the patient's need for treatment for alcohol problems"
* #drugs.D31 "D31. Interviewer severity rating: the patient's need for treatment for drug problems"
* #drugs.D32 "D32. Is the above information significantly distorted by the client's misrepresentation?"
* #drugs.D33 "D33. Is the above information significantly distorted by the client's inability to ..."
  * ^definition = "D33. Is the above information significantly distorted by the client's inability to understand?"
* #drugs.D34 "D34. Is the above information significantly distorted by the patient's resistance to ..."
  * ^definition = "D34. Is the above information significantly distorted by the patient's resistance to treatment?"
* #drugs.comments "Further information and comments (quote the question number)"
* #legal.L1 "L1. Was this admission prompted or suggested by the criminal justice system?"
* #legal.L2 "L2. Are you on probation?"
* #legal.L3 "L3. Shoplifting or vandalism"
* #legal.L4 "L4. Parole or probation violations"
* #legal.L5 "L5. Drug charges"
* #legal.L6 "L6. Forgery"
* #legal.L7 "L7. Weapons offence"
* #legal.L8 "L8. Stealing, breaking and entering"
* #legal.L9 "L9. Robbery"
* #legal.L10 "L10. Assault"
* #legal.L11 "L11. Arson"
* #legal.L12 "L12. Rape"
* #legal.L13 "L13. Homicide or manslaughter"
* #legal.L14 "L14. Prostitution"
* #legal.L15 "L15. Contempt of court"
* #legal.L16 "L16. Disorderly conduct, vagrancy, public intoxication"
* #legal.L17 "L17. Driving while intoxicated"
* #legal.L18 "L18. Major driving violations — speeding, reckless driving, no licence"
* #legal.L19 "L19. Other charges"
* #legal.L19s "L19. If other, specify"
* #legal.L20 "L20. Which of these charges resulted in convictions?"
* #legal.L21 "L21. How many months were you incarcerated in your life?"
* #legal.L22 "L22. How long was your last incarceration? (of 2 weeks or more)"
* #legal.L23 "L23. What was it for?"
* #legal.L24 "L24. Are you presently awaiting charges, trial or sentence?"
* #legal.L25 "L25. What for?"
* #legal.L26 "L26. How many days in the past 30 were you detained or incarcerated?"
* #legal.L27 "L27. How many days in the past 30 have you engaged in illegal activities for profit?"
* #legal.L28 "L28. How serious do you feel your present legal problems are?"
* #legal.L29 "L29. How important to you now is counselling or referral for these legal problems?"
* #legal.L30 "L30. Interviewer severity rating: the patient's need for legal services or counselling"
* #legal.L31 "L31. Is the above information significantly distorted by the client's misrepresentation?"
* #legal.L32 "L32. Is the above information significantly distorted by the client's inability to ..."
  * ^definition = "L32. Is the above information significantly distorted by the client's inability to understand?"
* #legal.L33 "L33. Is the above information significantly distorted by the patient's resistance to ..."
  * ^definition = "L33. Is the above information significantly distorted by the patient's resistance to treatment?"
* #legal.comments "Further information and comments (quote the question number)"
* #family.F1 "F1. Marital status"
* #family.F2 "F2. How long have you been in this marital status?"
* #family.F3 "F3. Are you satisfied with this situation?"
* #family.F4 "F4. Usual living arrangements over the past 3 years"
* #family.F5 "F5. How long have you lived in these arrangements?"
* #family.F6 "F6. Are you satisfied with these arrangements?"
* #family.F7 "F7. Do you live with anyone who has a current alcohol problem?"
* #family.F8 "F8. Do you live with anyone who uses non-prescribed drugs, or abuses prescribed drugs?"
* #family.F9 "F9. With whom do you spend most of your free time?"
* #family.F10 "F10. Are you satisfied with spending your free time this way?"
* #family.F11 "F11. How many close friends do you have?"
* #family.F12 "F12. Mother"
* #family.F13 "F13. Father"
* #family.F14 "F14. Brothers or sisters"
* #family.F15 "F15. Sexual partner or spouse"
* #family.F16 "F16. Children"
* #family.F17 "F17. Friends"
* #family.F18 "F18. Mother"
* #family.F19 "F19. Father"
* #family.F20 "F20. Brothers or sisters"
* #family.F21 "F21. Sexual partner or spouse"
* #family.F22 "F22. Children"
* #family.F23 "F23. Other significant family"
* #family.F24 "F24. Close friends"
* #family.F25 "F25. Neighbours"
* #family.F26 "F26. Co-workers"
* #family.F23s "F23. Other significant family — specify"
* #family.F27.past30 "F27. Emotionally — in the past 30 days"
* #family.F27.lifetime "F27. Emotionally — in your life"
* #family.F28.past30 "F28. Physically — in the past 30 days"
* #family.F28.lifetime "F28. Physically — in your life"
* #family.F29.past30 "F29. Sexually — in the past 30 days"
* #family.F29.lifetime "F29. Sexually — in your life"
* #family.F30 "F30. How many days in the past 30 have you had serious conflicts with your family?"
* #family.F31 "F31. How many days in the past 30 have you had serious conflicts with other people?"
* #family.F32 "F32. How troubled or bothered have you been in the past 30 days by family problems?"
* #family.F33 "F33. How troubled or bothered have you been in the past 30 days by social problems?"
* #family.F34 "F34. How important to you now is treatment or counselling for these family problems?"
* #family.F35 "F35. How important to you now is treatment or counselling for these social problems?"
* #family.F36 "F36. Interviewer severity rating: the patient's need for family or social counselling"
* #family.F37 "F37. Is the above information significantly distorted by the client's misrepresentation?"
* #family.F38 "F38. Is the above information significantly distorted by the client's inability to ..."
  * ^definition = "F38. Is the above information significantly distorted by the client's inability to understand?"
* #family.F39 "F39. Is the above information significantly distorted by the patient's resistance to ..."
  * ^definition = "F39. Is the above information significantly distorted by the patient's resistance to treatment?"
* #family.comments "Further information and comments (quote the question number)"
* #psychiatric.P1 "P1. How many times have you been treated for psychological or emotional problems in a ..."
  * ^definition = "P1. How many times have you been treated for psychological or emotional problems in a hospital or inpatient setting?"
* #psychiatric.P2 "P2. How many times have you been treated for psychological or emotional problems as an ..."
  * ^definition = "P2. How many times have you been treated for psychological or emotional problems as an outpatient or private patient?"
* #psychiatric.P4 "P4. Experienced serious depression — sadness, hopelessness, loss of interest, difficulty ..."
  * ^definition = "P4. Experienced serious depression — sadness, hopelessness, loss of interest, difficulty with daily functioning"
* #psychiatric.P5 "P5. Experienced serious anxiety or tension — uptight, unreasonably worried, unable to ..."
  * ^definition = "P5. Experienced serious anxiety or tension — uptight, unreasonably worried, unable to feel relaxed"
* #psychiatric.P6 "P6. Experienced hallucinations — saw things or heard voices that others did not"
* #psychiatric.P7 "P7. Experienced trouble understanding, concentrating or remembering"
* #psychiatric.P8 "P8. Experienced trouble controlling violent behaviour, including episodes of rage or ..."
  * ^definition = "P8. Experienced trouble controlling violent behaviour, including episodes of rage or violence"
* #psychiatric.P9 "P9. Experienced serious thoughts of suicide"
* #psychiatric.P10 "P10. Attempted suicide"
* #psychiatric.P11 "P11. Been prescribed medication for any psychological or emotional problem"
* #psychiatric.P12 "P12. How many days in the past 30 have you experienced these psychological or emotional ..."
  * ^definition = "P12. How many days in the past 30 have you experienced these psychological or emotional problems?"
* #psychiatric.P13 "P13. How much have you been troubled or bothered by these psychological or emotional ..."
  * ^definition = "P13. How much have you been troubled or bothered by these psychological or emotional problems in the past 30 days?"
* #psychiatric.P14 "P14. How important to you now is treatment for these psychological problems?"
* #psychiatric.P15 "P15. Obviously depressed or withdrawn"
* #psychiatric.P16 "P16. Obviously hostile"
* #psychiatric.P17 "P17. Obviously anxious or nervous"
* #psychiatric.P18 "P18. Having trouble with reality testing, thought disorders or paranoid thinking"
* #psychiatric.P19 "P19. Having trouble comprehending, concentrating or remembering"
* #psychiatric.P20 "P20. Having suicidal thoughts"
* #psychiatric.P21 "P21. Interviewer severity rating: the patient's need for psychiatric or psychological ..."
  * ^definition = "P21. Interviewer severity rating: the patient's need for psychiatric or psychological treatment"
* #psychiatric.P22 "P22. Is the above information significantly distorted by the client's misrepresentation?"
* #psychiatric.P23 "P23. Is the above information significantly distorted by the client's inability to ..."
  * ^definition = "P23. Is the above information significantly distorted by the client's inability to understand?"
* #psychiatric.P24 "P24. Is the above information significantly distorted by the patient's resistance to ..."
  * ^definition = "P24. Is the above information significantly distorted by the patient's resistance to treatment?"
* #psychiatric.comments "Further information and comments (quote the question number)"

// ── Addiction severity index answers ──
* #G8-1 "Patient terminated"
* #G8-2 "Patient refused"
* #G8-3 "Patient unable to respond"
* #G8-4 "Other"
* #G9-1 "Parents"
* #G9-2 "Spouse"
* #G9-3 "Alone"
* #G9-4 "Sibling or relative"
* #G9-5 "Friends"
* #G9-6 "Other"
* #G10-0 "You"
* #G10-1 "Parents"
* #G10-2 "Others"
* #G11-1 "0–3 months"
* #G11-2 "3–6 months"
* #G11-3 "6 months to one year"
* #G11-4 "One year and above"
* #G12-1 "Protestant"
* #G12-2 "Catholic"
* #G12-3 "Islamic"
* #G12-4 "Jewish"
* #G12-5 "Other"
* #G12-6 "None"
* #G13-1 "No"
* #G13-2 "Jail or prison"
* #G13-3 "Psychiatric treatment"
* #G13-4 "Medical treatment"
* #G13-5 "Alcohol or drug treatment"
* #G13-6 "Other"
* #G14-1 "0–7 days"
* #G14-2 "7–14 days"
* #G14-3 "14 days and above"
* #M3-0 "No"
* #M3-1 "Yes"
* #M4-0 "No"
* #M4-1 "Yes"
* #M6-0 "0 — Not at all"
* #M6-1 "1 — Slightly"
* #M6-2 "2 — Moderately"
* #M6-3 "3 — Considerably"
* #M6-4 "4 — Extremely"
* #M7-0 "0 — Not at all"
* #M7-1 "1 — Slightly"
* #M7-2 "2 — Moderately"
* #M7-3 "3 — Considerably"
* #M7-4 "4 — Extremely"
* #M8-0 "0 — No real problem, treatment not indicated"
* #M8-1 "1 — No real problem, treatment not indicated"
* #M8-2 "2 — Slight problem, treatment probably not necessary"
* #M8-3 "3 — Slight problem, treatment probably not necessary"
* #M8-4 "4 — Moderate problem, some treatment indicated"
* #M8-5 "5 — Moderate problem, some treatment indicated"
* #M8-6 "6 — Considerable problem, treatment necessary"
* #M8-7 "7 — Considerable problem, treatment necessary"
* #M8-8 "8 — Extreme problem, treatment absolutely necessary"
* #M8-9 "9 — Extreme problem, treatment absolutely necessary"
* #M9-0 "No"
* #M9-1 "Yes"
* #M10-0 "No"
* #M10-1 "Yes"
* #M11-0 "No"
* #M11-1 "Yes"
* #E3-0 "No"
* #E3-1 "Yes"
* #E4-0 "No"
* #E4-1 "Yes"
* #E5-0 "No"
* #E5-1 "Yes"
* #E7-0 "No"
* #E7-1 "Yes"
* #E8-0 "No"
* #E8-1 "Yes"
* #E9-1 "Full time (35+ hours)"
* #E9-2 "Retired or on disability"
* #E9-3 "Unemployed"
* #E9-4 "Student"
* #E9-5 "Military service"
* #E9-6 "Part time (irregular hours)"
* #E9-7 "Part time (regular hours)"
* #E9-8 "In a controlled environment"
* #E12-0 "0 — Not at all"
* #E12-1 "1 — Slightly"
* #E12-2 "2 — Moderately"
* #E12-3 "3 — Considerably"
* #E12-4 "4 — Extremely"
* #E13-0 "0 — Not at all"
* #E13-1 "1 — Slightly"
* #E13-2 "2 — Moderately"
* #E13-3 "3 — Considerably"
* #E13-4 "4 — Extremely"
* #E14-0 "0 — No real problem, treatment not indicated"
* #E14-1 "1 — No real problem, treatment not indicated"
* #E14-2 "2 — Slight problem, treatment probably not necessary"
* #E14-3 "3 — Slight problem, treatment probably not necessary"
* #E14-4 "4 — Moderate problem, some treatment indicated"
* #E14-5 "5 — Moderate problem, some treatment indicated"
* #E14-6 "6 — Considerable problem, treatment necessary"
* #E14-7 "7 — Considerable problem, treatment necessary"
* #E14-8 "8 — Extreme problem, treatment absolutely necessary"
* #E14-9 "9 — Extreme problem, treatment absolutely necessary"
* #E15-0 "No"
* #E15-1 "Yes"
* #E16-0 "No"
* #E16-1 "Yes"
* #E17-0 "No"
* #E17-1 "Yes"
* #route-1 "Oral"
* #route-2 "Nasal"
* #route-3 "Smoking"
* #route-4 "Non-IV injection"
* #route-5 "IV"
* #D26-0 "0 — Not at all"
* #D26-1 "1 — Slightly"
* #D26-2 "2 — Moderately"
* #D26-3 "3 — Considerably"
* #D26-4 "4 — Extremely"
* #D27-0 "0 — Not at all"
* #D27-1 "1 — Slightly"
* #D27-2 "2 — Moderately"
* #D27-3 "3 — Considerably"
* #D27-4 "4 — Extremely"
* #D28-0 "0 — Not at all"
* #D28-1 "1 — Slightly"
* #D28-2 "2 — Moderately"
* #D28-3 "3 — Considerably"
* #D28-4 "4 — Extremely"
* #D29-0 "0 — Not at all"
* #D29-1 "1 — Slightly"
* #D29-2 "2 — Moderately"
* #D29-3 "3 — Considerably"
* #D29-4 "4 — Extremely"
* #D30-0 "0 — No real problem, treatment not indicated"
* #D30-1 "1 — No real problem, treatment not indicated"
* #D30-2 "2 — Slight problem, treatment probably not necessary"
* #D30-3 "3 — Slight problem, treatment probably not necessary"
* #D30-4 "4 — Moderate problem, some treatment indicated"
* #D30-5 "5 — Moderate problem, some treatment indicated"
* #D30-6 "6 — Considerable problem, treatment necessary"
* #D30-7 "7 — Considerable problem, treatment necessary"
* #D30-8 "8 — Extreme problem, treatment absolutely necessary"
* #D30-9 "9 — Extreme problem, treatment absolutely necessary"
* #D31-0 "0 — No real problem, treatment not indicated"
* #D31-1 "1 — No real problem, treatment not indicated"
* #D31-2 "2 — Slight problem, treatment probably not necessary"
* #D31-3 "3 — Slight problem, treatment probably not necessary"
* #D31-4 "4 — Moderate problem, some treatment indicated"
* #D31-5 "5 — Moderate problem, some treatment indicated"
* #D31-6 "6 — Considerable problem, treatment necessary"
* #D31-7 "7 — Considerable problem, treatment necessary"
* #D31-8 "8 — Extreme problem, treatment absolutely necessary"
* #D31-9 "9 — Extreme problem, treatment absolutely necessary"
* #D32-0 "No"
* #D32-1 "Yes"
* #D33-0 "No"
* #D33-1 "Yes"
* #D34-0 "No"
* #D34-1 "Yes"
* #L1-0 "No"
* #L1-1 "Yes"
* #L2-0 "No"
* #L2-1 "Yes"
* #L24-0 "No"
* #L24-1 "Yes"
* #L28-0 "0 — Not at all"
* #L28-1 "1 — Slightly"
* #L28-2 "2 — Moderately"
* #L28-3 "3 — Considerably"
* #L28-4 "4 — Extremely"
* #L29-0 "0 — Not at all"
* #L29-1 "1 — Slightly"
* #L29-2 "2 — Moderately"
* #L29-3 "3 — Considerably"
* #L29-4 "4 — Extremely"
* #L30-0 "0 — No real problem, treatment not indicated"
* #L30-1 "1 — No real problem, treatment not indicated"
* #L30-2 "2 — Slight problem, treatment probably not necessary"
* #L30-3 "3 — Slight problem, treatment probably not necessary"
* #L30-4 "4 — Moderate problem, some treatment indicated"
* #L30-5 "5 — Moderate problem, some treatment indicated"
* #L30-6 "6 — Considerable problem, treatment necessary"
* #L30-7 "7 — Considerable problem, treatment necessary"
* #L30-8 "8 — Extreme problem, treatment absolutely necessary"
* #L30-9 "9 — Extreme problem, treatment absolutely necessary"
* #L31-0 "No"
* #L31-1 "Yes"
* #L32-0 "No"
* #L32-1 "Yes"
* #L33-0 "No"
* #L33-1 "Yes"
* #F1-1 "Married"
* #F1-2 "Remarried"
* #F1-3 "Widowed"
* #F1-4 "Separated"
* #F1-5 "Divorced"
* #F1-6 "Never married"
* #F3-0 "No"
* #F3-1 "Indifferent"
* #F3-2 "Yes"
* #F4-1 "With sexual partner and children"
* #F4-2 "With sexual partner alone"
* #F4-3 "With children alone"
* #F4-4 "With parents"
* #F4-5 "With siblings"
* #F4-6 "With friends"
* #F4-7 "Alone"
* #F4-8 "Controlled environment"
* #F4-9 "No stable arrangement"
* #F6-0 "No"
* #F6-1 "Indifferent"
* #F6-2 "Yes"
* #F7-0 "No"
* #F7-1 "Yes"
* #F8-0 "No"
* #F8-1 "Yes"
* #F9-1 "Family"
* #F9-2 "Friends"
* #F9-3 "Alone"
* #F10-0 "No"
* #F10-1 "Indifferent"
* #F10-2 "Yes"
* #F12-0 "Clearly no for all in class"
* #F12-1 "Clearly yes for any in class"
* #F12-2 "Uncertain or don't know"
* #F12-3 "Never was a relative"
* #F13-0 "Clearly no for all in class"
* #F13-1 "Clearly yes for any in class"
* #F13-2 "Uncertain or don't know"
* #F13-3 "Never was a relative"
* #F14-0 "Clearly no for all in class"
* #F14-1 "Clearly yes for any in class"
* #F14-2 "Uncertain or don't know"
* #F14-3 "Never was a relative"
* #F15-0 "Clearly no for all in class"
* #F15-1 "Clearly yes for any in class"
* #F15-2 "Uncertain or don't know"
* #F15-3 "Never was a relative"
* #F16-0 "Clearly no for all in class"
* #F16-1 "Clearly yes for any in class"
* #F16-2 "Uncertain or don't know"
* #F16-3 "Never was a relative"
* #F17-0 "Clearly no for all in class"
* #F17-1 "Clearly yes for any in class"
* #F17-2 "Uncertain or don't know"
* #F17-3 "Never was a relative"
* #F18-0 "No"
* #F18-1 "Yes"
* #F19-0 "No"
* #F19-1 "Yes"
* #F20-0 "No"
* #F20-1 "Yes"
* #F21-0 "No"
* #F21-1 "Yes"
* #F22-0 "No"
* #F22-1 "Yes"
* #F23-0 "No"
* #F23-1 "Yes"
* #F24-0 "No"
* #F24-1 "Yes"
* #F25-0 "No"
* #F25-1 "Yes"
* #F26-0 "No"
* #F26-1 "Yes"
* #past30-0 "No"
* #past30-1 "Yes"
* #lifetime-0 "No"
* #lifetime-1 "Yes"
* #F32-0 "0 — Not at all"
* #F32-1 "1 — Slightly"
* #F32-2 "2 — Moderately"
* #F32-3 "3 — Considerably"
* #F32-4 "4 — Extremely"
* #F33-0 "0 — Not at all"
* #F33-1 "1 — Slightly"
* #F33-2 "2 — Moderately"
* #F33-3 "3 — Considerably"
* #F33-4 "4 — Extremely"
* #F34-0 "0 — Not at all"
* #F34-1 "1 — Slightly"
* #F34-2 "2 — Moderately"
* #F34-3 "3 — Considerably"
* #F34-4 "4 — Extremely"
* #F35-0 "0 — Not at all"
* #F35-1 "1 — Slightly"
* #F35-2 "2 — Moderately"
* #F35-3 "3 — Considerably"
* #F35-4 "4 — Extremely"
* #F36-0 "0 — No real problem, treatment not indicated"
* #F36-1 "1 — No real problem, treatment not indicated"
* #F36-2 "2 — Slight problem, treatment probably not necessary"
* #F36-3 "3 — Slight problem, treatment probably not necessary"
* #F36-4 "4 — Moderate problem, some treatment indicated"
* #F36-5 "5 — Moderate problem, some treatment indicated"
* #F36-6 "6 — Considerable problem, treatment necessary"
* #F36-7 "7 — Considerable problem, treatment necessary"
* #F36-8 "8 — Extreme problem, treatment absolutely necessary"
* #F36-9 "9 — Extreme problem, treatment absolutely necessary"
* #F37-0 "No"
* #F37-1 "Yes"
* #F38-0 "No"
* #F38-1 "Yes"
* #F39-0 "No"
* #F39-1 "Yes"
* #P4-0 "No"
* #P4-1 "Yes"
* #P5-0 "No"
* #P5-1 "Yes"
* #P6-0 "No"
* #P6-1 "Yes"
* #P7-0 "No"
* #P7-1 "Yes"
* #P8-0 "No"
* #P8-1 "Yes"
* #P9-0 "No"
* #P9-1 "Yes"
* #P10-0 "No"
* #P10-1 "Yes"
* #P11-0 "No"
* #P11-1 "Yes"
* #P13-0 "0 — Not at all"
* #P13-1 "1 — Slightly"
* #P13-2 "2 — Moderately"
* #P13-3 "3 — Considerably"
* #P13-4 "4 — Extremely"
* #P14-0 "0 — Not at all"
* #P14-1 "1 — Slightly"
* #P14-2 "2 — Moderately"
* #P14-3 "3 — Considerably"
* #P14-4 "4 — Extremely"
* #P15-0 "No"
* #P15-1 "Yes"
* #P16-0 "No"
* #P16-1 "Yes"
* #P17-0 "No"
* #P17-1 "Yes"
* #P18-0 "No"
* #P18-1 "Yes"
* #P19-0 "No"
* #P19-1 "Yes"
* #P20-0 "No"
* #P20-1 "Yes"
* #P21-0 "0 — No real problem, treatment not indicated"
* #P21-1 "1 — No real problem, treatment not indicated"
* #P21-2 "2 — Slight problem, treatment probably not necessary"
* #P21-3 "3 — Slight problem, treatment probably not necessary"
* #P21-4 "4 — Moderate problem, some treatment indicated"
* #P21-5 "5 — Moderate problem, some treatment indicated"
* #P21-6 "6 — Considerable problem, treatment necessary"
* #P21-7 "7 — Considerable problem, treatment necessary"
* #P21-8 "8 — Extreme problem, treatment absolutely necessary"
* #P21-9 "9 — Extreme problem, treatment absolutely necessary"
* #P22-0 "No"
* #P22-1 "Yes"
* #P23-0 "No"
* #P23-1 "Yes"
* #P24-0 "No"
* #P24-1 "Yes"

// ── Beck depression inventory answers (code suffix after the dash is the score) ──
* #bdi.1-0 "I do not feel sad."
* #bdi.1-1 "I feel sad."
* #bdi.1-2 "I am sad all the time and I can't snap out of it."
* #bdi.1-3 "I am so sad and unhappy that I can't stand it."
* #bdi.2-0 "I am not particularly discouraged about the future."
* #bdi.2-1 "I feel discouraged about the future."
* #bdi.2-2 "I feel I have nothing to look forward to."
* #bdi.2-3 "I feel the future is hopeless and that things cannot improve."
* #bdi.3-0 "I do not feel like a failure."
* #bdi.3-1 "I feel I have failed more than the average person."
* #bdi.3-2 "As I look back on my life, all I can see is a lot of failures."
* #bdi.3-3 "I feel I am a complete failure as a person."
* #bdi.4-0 "I get as much satisfaction out of things as I used to."
* #bdi.4-1 "I don't enjoy things the way I used to."
* #bdi.4-2 "I don't get real satisfaction out of anything anymore."
* #bdi.4-3 "I am dissatisfied or bored with everything."
* #bdi.5-0 "I don't feel particularly guilty."
* #bdi.5-1 "I feel guilty a good part of the time."
* #bdi.5-2 "I feel quite guilty most of the time."
* #bdi.5-3 "I feel guilty all of the time."
* #bdi.6-0 "I don't feel I am being punished."
* #bdi.6-1 "I feel I may be punished."
* #bdi.6-2 "I expect to be punished."
* #bdi.6-3 "I feel I am being punished."
* #bdi.7-0 "I don't feel disappointed in myself."
* #bdi.7-1 "I am disappointed in myself."
* #bdi.7-2 "I am disgusted with myself."
* #bdi.7-3 "I hate myself."
* #bdi.8-0 "I don't feel I am any worse than anybody else."
* #bdi.8-1 "I am critical of myself for my weaknesses or mistakes."
* #bdi.8-2 "I blame myself all the time for my faults."
* #bdi.8-3 "I blame myself for everything bad that happens."
* #bdi.9-0 "I don't have any thoughts of killing myself."
* #bdi.9-1 "I have thoughts of killing myself, but I would not carry them out."
* #bdi.9-2 "I would like to kill myself."
* #bdi.9-3 "I would kill myself if I had the chance."
* #bdi.10-0 "I don't cry any more than usual."
* #bdi.10-1 "I cry more now than I used to."
* #bdi.10-2 "I cry all the time now."
* #bdi.10-3 "I used to be able to cry, but now I can't cry even though I want to."
* #bdi.11-0 "I am no more irritated by things than I ever was."
* #bdi.11-1 "I am slightly more irritated now than usual."
* #bdi.11-2 "I am quite annoyed or irritated a good deal of the time."
* #bdi.11-3 "I feel irritated all the time."
* #bdi.12-0 "I have not lost interest in other people."
* #bdi.12-1 "I am less interested in other people than I used to be."
* #bdi.12-2 "I have lost most of my interest in other people."
* #bdi.12-3 "I have lost all of my interest in other people."
* #bdi.13-0 "I make decisions about as well as I ever could."
* #bdi.13-1 "I put off making decisions more than I used to."
* #bdi.13-2 "I have greater difficulty in making decisions than I used to."
* #bdi.13-3 "I can't make decisions at all anymore."
* #bdi.14-0 "I don't feel that I look any worse than I used to."
* #bdi.14-1 "I am worried that I am looking old or unattractive."
* #bdi.14-2 "I feel there are permanent changes in my appearance that make me look unattractive."
* #bdi.14-3 "I believe that I look ugly."
* #bdi.15-0 "I can work about as well as before."
* #bdi.15-1 "It takes an extra effort to get started at doing something."
* #bdi.15-2 "I have to push myself very hard to do anything."
* #bdi.15-3 "I can't do any work at all."
* #bdi.16-0 "I can sleep as well as usual."
* #bdi.16-1 "I don't sleep as well as I used to."
* #bdi.16-2 "I wake up 1-2 hours earlier than usual and find it hard to get back to sleep."
* #bdi.16-3 "I wake up several hours earlier than I used to and cannot get back to sleep."
* #bdi.17-0 "I don't get more tired than usual."
* #bdi.17-1 "I get tired more easily than I used to."
* #bdi.17-2 "I get tired from doing almost anything."
* #bdi.17-3 "I am too tired to do anything."
* #bdi.18-0 "My appetite is no worse than usual."
* #bdi.18-1 "My appetite is not as good as it used to be."
* #bdi.18-2 "My appetite is much worse now."
* #bdi.18-3 "I have no appetite at all anymore."
* #bdi.19-0 "I haven't lost much weight, if any, lately."
* #bdi.19-1 "I have lost more than five pounds."
* #bdi.19-2 "I have lost more than ten pounds."
* #bdi.19-3 "I have lost more than fifteen pounds."
* #bdi.20-0 "I am no more worried about my health than usual."
* #bdi.20-1 "I am worried about physical problems like aches, pains, upset stomach or constipation."
* #bdi.20-2 "I am very worried about physical problems and it's hard to think of much else."
* #bdi.20-3 "I am so worried about my physical problems that I cannot think of anything else."
* #bdi.21-0 "I have not noticed any recent change in my interest in sex."
* #bdi.21-1 "I am less interested in sex than I used to be."
* #bdi.21-2 "I have almost no interest in sex."
* #bdi.21-3 "I have lost interest in sex completely."

// ── Clinical and psychological history questions ──
* #examination.pallor "Pallor"
* #examination.oedema "Oedema"
* #examination.dehydration "Dehydration"
* #examination.oralThrush "Oral thrush"
* #examination.cyanosis "Cyanosis"
* #history.presentingProblem "The presenting problem, allegations or reasons for admission"
* #history.historyOfPresenting "History of the presenting problem"
* #history.pastPsychiatric "Past psychiatric history and previous treatment"
* #history.pastMedical "Past medical and surgical history and treatment, including vegetative signs"
* #history.family "Family history"
* #history.developmental "Developmental history — prenatal where possible, birth, childhood milestones, schooling ..."
  * ^definition = "Developmental history — prenatal where possible, birth, childhood milestones, schooling, occupation"
* #history.social "Social and interpersonal relationships"
* #history.sexuality "Sexuality and sexual history"
* #history.suicidality "Suicidality"
* #mse.appearanceBehaviour "Appearance and behaviour"
* #mse.attitude "Attitude"
* #mse.grooming "General appearance and grooming"
* #mse.facialExpression "Facial expression"
* #mse.posture "Posture"
* #mse.gait "Gait"
* #mse.psychomotor "Psychomotor activity"
* #mse.speech "Voice, speech and language"
* #mse.mood "Mood"
* #mse.affect "Affect"
* #mse.thought "Thought content and process"
* #mse.perception "Perception"
* #mse.cognition "Cognitive processes"
* #mse.orientationTime "Orientation — time"
* #mse.orientationPeople "Orientation — people"
* #mse.orientationPlace "Orientation — place"
* #mse.consciousness "Level of consciousness"
* #mse.attention "Attention and concentration"
* #mse.memoryImmediate "Memory — immediate"
* #mse.memoryRecent "Memory — recent"
* #mse.memoryPast "Memory — past"
* #mse.insightJudgment "Insight and judgment"
* #formulation.diagnostic "Diagnostic formulation"
* #formulation.impression "Impression"
* #formulation.treatmentPlan "Treatment plan"

// ── Note section headings ──
* #part1.soap.subjective "Subjective"
* #part1.soap.objective "Objective"
* #part1.soap.assessment "Assessment"
* #part1.soap.plan "Plan"
* #part2.summary "Admission summary"
* #part2.recommendation "Recommendation"
* #soap.subjective "Subjective"
* #soap.objective "Objective"
* #soap.assessment "Assessment"
* #soap.plan "Plan"
* #progress "Progress"
* #stuckPoint.issue "Stuck point"
* #stuckPoint.intervention "Intervention"
* #stuckPoint.objective "Objective"

// ── Case conference problem categories ──
* #primaryAddiction "Primary addiction"
* #secondaryAddiction "Secondary addiction"
* #medicalProblem "Active medical problem"
* #psychiatricCondition "Psychiatric condition"

// ── Stages of change ──
* #pre-contemplative "Pre-contemplative"
* #contemplative "Contemplative"
* #decisional "Decisional"
* #action "Action"
* #maintenance "Maintenance"

// ── Vital status of a family member ──
* #alive "Alive"
* #dead "Deceased"

// ── Aftercare contact persons ──
* #self "Self"
* #significant-other "Significant other"
